### ISSUE TITLE
Can no longer compile dnscrypt-mipsel-static

### ISSUE THREAD

**Issue by leandroong** [lancethepants/dnscrypt-mipsel-static#2]
configure: error: libsodium >= 0.5.0 not found
Note: I'm using latest commit for both libsodium and dnscrypt-proxy on site https://github.com/jedisct1?tab=repositories

**Comment by leandroong** [comment]
For the meantime, I shifted back to entware for compilation. I do notice that "hostip" compilation is removed, only dnscrypt-proxy is compiled, does it mean that hostip not needed?

**Comment by ryzhovau** [comment]
See https://github.com/Entware/entware/issues/144

**Comment by lancethepants** [comment]
I use this script to create and distribute binaries of tagged release tarballs. Some tweaking may be required on your part if you deviate from or modify it.
